wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    code_path: code/main_nfm.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.13
    start_time: 1654559424
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      4: 3.7.13
      5: 0.12.17
      8:
      - 2
      - 3
      - 5
